### ISSUE TITLE
[Bug] Import Failed error

### ISSUE THREAD

**Issue by ricardofeynman** [jags111/ComfyUI_Jags_Audiotools#1]
Thanks for releasing, I'm really excited about this one! I'm unsure if your note in the Readme is a request not to post bug issues yet... Sorry if I'm jumping the gun but just in case this helps:

Traceback (most recent call last):
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/__init__.py", line 23, in <module>
    from .SampleDiffusion import *
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/SampleDiffusion.py", line 122, in <module>
    libs = os.path.join(comfy_dir, 'custom_nodes/ComfyUI_Jags_Audiotools/libs')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Cannot import /home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools module for custom nodes: expected str, bytes or os.PathLike object, not NoneType

**Comment by GentlemanHu** [comment]
same here.

```python
Traceback (most recent call last):
  File "/content/drive/colab_ai/ComfyUI/nodes.py", line 1805, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/__init__.py", line 23, in <module>
    from .SampleDiffusion import *
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/SampleDiffusion.py", line 122, in <module>
    libs = os.path.join(comfy_dir, 'custom_nodes/ComfyUI_Jags_Audiotools/libs')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Cannot import /content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools module for custom nodes: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by jags111** [comment]
Hai the init py is getting updated and will post a note here so you can correct same and update. Only one node is failing and that is save audio node all rest is fine and will rerun a check and update again

**Comment by jags111** [comment]
I have updated all the files and checked same for any errors and kindly have an update or reinstall and check same. All errors are eliminated. Only one major change  I will do now is naming all TENSOR to AUDIO so no confusion.

**Comment by ricardofeynman** [comment]
Thanks, I've given the newest commit a try, but am still getting an import failure with a different error message. 

I have attached the edited version of my notetaking from the terminal as I worked through trying to resolve the errors. It should offer some insight as to where the issue is occuring. I have noted my suspicions in the txt file, but no clear picture yet...
 
[AUDIOTOOLS DEBUG EDITED.txt](https://github.com/jags111/ComfyUI_Jags_Audiotools/files/13672732/AUDIOTOOLS.DEBUG.EDITED.txt)

I still have a few things to try after some wreckless pip installing messed up a few additional nodes... After resolving most of the version conflicts that caused, when I'm launching ComfyUI at present the only import fail / error thrown in the terminal now relates to the Audiotools custom nodes. 

Current error is at the bottom of the attached txt file. 

Do you know whether - Cannot import ..... ComfyUI_Jags_Audiotools module for custom nodes: 'ComfyUIManagerLogger' object has no attribute 'isatty' - is possibly something to do with a missing dependency in " diffusion 6.10.1"  which i'm presently having to address some conflicts with?

**Comment by ricardofeynman** [comment]
Thanks, I've just given the newest version a try, both as an upgrade, and then as a fresh install to custom nodes via the manager. Both ways of updating to the newest commit still unfortunately give the error attached:

[AUDIOTOOLS ISATTY IMPORT ERROR.txt](https://github.com/jags111/ComfyUI_Jags_Audiotools/files/13692363/AUDIOTOOLS.ISATTY.IMPORT.ERROR.txt)

**Comment by ricardofeynman** [comment]
@jags111 Hi I've tried out the newest 110C from an hour ago and I'm still getting that same error:

Copying JS files for Workflow loading
Traceback (most recent call last):
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/__init__.py", line 23, in <module>
    from .SampleDiffusion import *
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/SampleDiffusion.py", line 44, in <module>
    hijack_import("diffusion", "v-diffusion-pytorch")
  File "/home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/SampleDiffusion.py", line 38, in hijack_import
    importlib.import_module(importname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/x/.local/lib/python3.10/site-packages/diffusion/__init__.py", line 4, in <module>
    from .internal.protocol import SessionId
  File "/home/x/.local/lib/python3.10/site-packages/diffusion/internal/protocol/__init__.py", line 14, in <module>
    import structlog
  File "/home/x/.local/lib/python3.10/site-packages/structlog/__init__.py", line 10, in <module>
    from structlog import dev, processors, stdlib, testing, threadlocal, types
  File "/home/x/.local/lib/python3.10/site-packages/structlog/stdlib.py", line 31, in <module>
    from ._config import get_logger as _generic_get_logger
  File "/home/x/.local/lib/python3.10/site-packages/structlog/_config.py", line 43, in <module>
    colors=_use_colors and sys.stdout is not None and sys.stdout.isatty()
AttributeError: 'ComfyUIManagerLogger' object has no attribute 'isatty'

Cannot import /home/x/Documents/_ComfyUI_2023-11-25_1735C/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools module for custom nodes: 'ComfyUIManagerLogger' object has no attribute 'isatty'


 I went looking into isatty for clues and found this https://github.com/rsalmei/alive-progress/issues/17#issuecomment-553581153 and this https://github.com/chriskiehl/Gooey/issues/879#issuecomment-1586511649

I think these threads could offer some insight into why the isatty exception is being thrown, and/or how to mitigate it.

**Comment by jags111** [comment]
hey  I think the issue is coming from the javascript and will edit same so it does not create further issues and close

**Comment by ricardofeynman** [comment]
Hi, I've just taken a moment to test and unfortunately I'm still getting the import error when updating to commit 112. I've attached the terminal readout from the install of 112 [283e169]

[JAGS AUDIOTOOLS FRESH INSTALL COMMIT 112.txt](https://github.com/jags111/ComfyUI_Jags_Audiotools/files/13756268/JAGS.AUDIOTOOLS.FRESH.INSTALL.COMMIT.112.txt)

**Comment by jags111** [comment]
Hai. Thanks for testing same and wonderful for your cooperation. I have modified all the code that was referencing same and added all fresh scripts in. Also some three nodes still have some issue that i am working on .. Other than that most of the nodes are loading fine.
<img width="761" alt="2023-12-26_21-47-55" src="https://github.com/jags111/ComfyUI_Jags_Audiotools/assets/5968619/bf6ac440-9a0a-4979-88f0-2fd9d933d2f6">

<img width="503" alt="2023-12-26_21-40-41" src="https://github.com/jags111/ComfyUI_Jags_Audiotools/assets/5968619/d1c1f92e-0147-4377-bf62-3fadcfa3135c">

**Comment by jags111** [comment]
let me know if any further error is reported thanks

**Comment by ricardofeynman** [comment]
WIll test right now, thanks.

**Comment by jags111** [comment]
hai please note some nodes are still having issues and trying to solve same. Thanks for your support.
