### ISSUE TITLE
Doesn't load on a headless server

### ISSUE THREAD

**Issue by Trojaner** [jags111/ComfyUI_Jags_Audiotools#15]
I'm trying to run your extension on a headless server. Since it's a headless server, there is no audio input or output device.
Is there any way to still use it?

Logs:
```
add ffmpeg to path
xcb_connection_has_error() returned true
Traceback (most recent call last):
  File "/home/ml/ComfyUI/nodes.py", line 2092, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ml/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/__init__.py", line 23, in <module>
    from .SampleDiffusion import *
  File "/home/ml/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools/SampleDiffusion.py", line 145, in <module>
    mixer.init()
pygame.error: Could not setup connection to PulseAudio

Cannot import /home/ml/ComfyUI/custom_nodes/ComfyUI_Jags_Audiotools module for custom nodes: Could not setup connection to PulseAudio
```

**Comment by Trojaner** [comment]
Problem is somehow gone after installing other nodes
